import { request } from "https";
import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export const getServerSideProps: GetServerSideProps = async (context) => {
  const response = await fetch("https://api.chucknorris.io/jokes/categories");
  const categoriesList = await response.json();
  if (categoriesList.length === 0) {
    return {
      notFound: true,
    };
  }

  return {
    props: {
      categories: categoriesList,
    },
  };
};
type CategoriesProps = {
  categories: string[];
};
const Home: React.FC<CategoriesProps> = ({ categories }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Chuck Noris Joke</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Chuck Noris Joke</h1>

        <p className={styles.description}>Categories</p>

        <div className={styles.grid}>
          {categories.map((e, index) => {
            return (
              <Link href={`/categories/${e}`} key={index}>
                <a className={styles.card}>
                  <h2> {e} &rarr;</h2>
                </a>
              </Link>
            );
          })}
        </div>
      </main>

      <footer className={styles.footer}>
        <div>Made by Miora</div>
      </footer>
    </div>
  );
};

export default Home;
